
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define NFSv4yyconst const
#else
#define NFSv4yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (NFSv4yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((NFSv4yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE NFSv4yyrestart(NFSv4yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(NFSv4yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct NFSv4yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int NFSv4yyleng;

extern FILE *NFSv4yyin, *NFSv4yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for NFSv4yy_rule_can_match_eol because it requires
     *       access to the local variable NFSv4yy_act. Since NFSv4yyless() is a macro, it would break
     *       existing scanners that call NFSv4yyless() from OUTSIDE NFSv4yylex. 
     *       One obvious solution it to make NFSv4yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-NFSv4yylineno scanner, because NFSv4yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int NFSv4yyl;\
                for ( NFSv4yyl = n; NFSv4yyl < NFSv4yyleng; ++NFSv4yyl )\
                    if ( NFSv4yytext[NFSv4yyl] == '\n' )\
                        --NFSv4yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define NFSv4yyless(n) \
	do \
		{ \
		/* Undo effects of setting up NFSv4yytext. */ \
        int NFSv4yyless_macro_arg = (n); \
        YY_LESS_LINENO(NFSv4yyless_macro_arg);\
		*NFSv4yy_cp = (NFSv4yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(NFSv4yy_c_buf_p) = NFSv4yy_cp = NFSv4yy_bp + NFSv4yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up NFSv4yytext again */ \
		} \
	while ( 0 )

#define unput(c) NFSv4yyunput( c, (NFSv4yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t NFSv4yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct NFSv4yy_buffer_state
	{
	FILE *NFSv4yy_input_file;

	char *NFSv4yy_ch_buf;		/* input buffer */
	char *NFSv4yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	NFSv4yy_size_t NFSv4yy_buf_size;

	/* Number of characters read into NFSv4yy_ch_buf, not including EOB
	 * characters.
	 */
	int NFSv4yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int NFSv4yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int NFSv4yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int NFSv4yy_at_bol;

    int NFSv4yy_bs_lineno; /**< The line count. */
    int NFSv4yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int NFSv4yy_fill_buffer;

	int NFSv4yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via NFSv4yyrestart()), so that the user can continue scanning by
	 * just pointing NFSv4yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t NFSv4yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t NFSv4yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * NFSv4yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (NFSv4yy_buffer_stack) \
                          ? (NFSv4yy_buffer_stack)[(NFSv4yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (NFSv4yy_buffer_stack)[(NFSv4yy_buffer_stack_top)]

/* NFSv4yy_hold_char holds the character lost when NFSv4yytext is formed. */
static char NFSv4yy_hold_char;
static int NFSv4yy_n_chars;		/* number of characters read into NFSv4yy_ch_buf */
int NFSv4yyleng;

/* Points to current character in buffer. */
static char *NFSv4yy_c_buf_p = (char *) 0;
static int NFSv4yy_init = 0;		/* whether we need to initialize */
static int NFSv4yy_start = 0;	/* start state number */

/* Flag which is used to allow NFSv4yywrap()'s to do buffer switches
 * instead of setting up a fresh NFSv4yyin.  A bit of a hack ...
 */
static int NFSv4yy_did_buffer_switch_on_eof;

void NFSv4yyrestart (FILE *input_file  );
void NFSv4yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE NFSv4yy_create_buffer (FILE *file,int size  );
void NFSv4yy_delete_buffer (YY_BUFFER_STATE b  );
void NFSv4yy_flush_buffer (YY_BUFFER_STATE b  );
void NFSv4yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void NFSv4yypop_buffer_state (void );

static void NFSv4yyensure_buffer_stack (void );
static void NFSv4yy_load_buffer_state (void );
static void NFSv4yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER NFSv4yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE NFSv4yy_scan_buffer (char *base,NFSv4yy_size_t size  );
YY_BUFFER_STATE NFSv4yy_scan_string (NFSv4yyconst char *NFSv4yy_str  );
YY_BUFFER_STATE NFSv4yy_scan_bytes (NFSv4yyconst char *bytes,int len  );

void *NFSv4yyalloc (NFSv4yy_size_t  );
void *NFSv4yyrealloc (void *,NFSv4yy_size_t  );
void NFSv4yyfree (void *  );

#define NFSv4yy_new_buffer NFSv4yy_create_buffer

#define NFSv4yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        NFSv4yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            NFSv4yy_create_buffer(NFSv4yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->NFSv4yy_is_interactive = is_interactive; \
	}

#define NFSv4yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        NFSv4yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            NFSv4yy_create_buffer(NFSv4yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->NFSv4yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->NFSv4yy_at_bol)

/* Begin user sect3 */

#define NFSv4yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *NFSv4yyin = (FILE *) 0, *NFSv4yyout = (FILE *) 0;

typedef int NFSv4yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int NFSv4yylineno;

int NFSv4yylineno = 1;

extern char NFSv4yytext[];

static NFSv4yy_state_type NFSv4yy_get_previous_state (void );
static NFSv4yy_state_type NFSv4yy_try_NUL_trans (NFSv4yy_state_type current_state  );
static int NFSv4yy_get_next_buffer (void );
static void NFSv4yy_fatal_error (NFSv4yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up NFSv4yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(NFSv4yytext_ptr) = NFSv4yy_bp; \
	NFSv4yyleng = (size_t) (NFSv4yy_cp - NFSv4yy_bp); \
	(NFSv4yy_hold_char) = *NFSv4yy_cp; \
	*NFSv4yy_cp = '\0'; \
	if ( NFSv4yyleng + (NFSv4yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	NFSv4yy_flex_strncpy( &NFSv4yytext[(NFSv4yy_more_offset)], (NFSv4yytext_ptr), NFSv4yyleng + 1 ); \
	NFSv4yyleng += (NFSv4yy_more_offset); \
	(NFSv4yy_prev_more_offset) = (NFSv4yy_more_offset); \
	(NFSv4yy_more_offset) = 0; \
	(NFSv4yy_c_buf_p) = NFSv4yy_cp;

#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct NFSv4yy_trans_info
	{
	flex_int32_t NFSv4yy_verify;
	flex_int32_t NFSv4yy_nxt;
	};
static NFSv4yyconst flex_int16_t NFSv4yy_acclist[50] =
    {   0,
       22,   20,   21,   18,   20,   21,   21,   20,   21,   17,
       20,   21,   20,   21,   20,   21,   20,   21,   20,   21,
       20,   21,   20,   21,   20,   21,   18,   19,   17,    5,
       15,   16,   17,   17,    2,    4,   17,    6,   12,    3,
       17,    7,    8,   13,   14,    9,    1,   10,   11
    } ;

static NFSv4yyconst flex_int16_t NFSv4yy_accept[58] =
    {   0,
        1,    1,    1,    2,    4,    7,    8,   10,   13,   15,
       17,   19,   21,   23,   25,   27,   28,   28,   29,   30,
       30,   31,   31,   31,   31,   31,   32,   33,   33,   33,
       33,   34,   35,   35,   35,   35,   35,   36,   36,   37,
       38,   39,   40,   41,   41,   41,   42,   43,   44,   45,
       46,   46,   47,   48,   49,   50,   50
    } ;

static NFSv4yyconst flex_int32_t NFSv4yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    5,    6,    7,    6,    6,    6,
        8,    6,    9,    6,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1,    5,    1,    6,   10,   11,   12,

       13,    6,    6,   14,   15,    6,   16,   17,   18,   19,
       20,   21,    6,   22,   23,    6,   24,    6,   25,    6,
       26,    6,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static NFSv4yyconst flex_int32_t NFSv4yy_meta[27] =
    {   0,
        1,    1,    1,    1,    2,    3,    4,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static NFSv4yyconst flex_int16_t NFSv4yy_base[62] =
    {   0,
        0,    0,   81,   82,   78,   82,   76,   71,   63,   54,
       59,   54,   50,    7,   15,   70,   68,   82,   63,   62,
       82,   58,   54,   47,   52,   82,   82,   53,   47,   39,
       54,    0,   51,   33,   45,   33,   82,   38,   82,   48,
       14,   16,   82,   42,   32,   31,   82,   82,   82,   82,
       14,   18,   82,   82,   82,   82,   41,   43,   46,   27,
       49
    } ;

static NFSv4yyconst flex_int16_t NFSv4yy_def[62] =
    {   0,
       56,    1,   56,   56,   56,   56,   57,   58,   56,   56,
       56,   56,   56,   56,   56,   56,   57,   56,   59,   58,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       59,   60,   56,   56,   56,   56,   56,   56,   56,   61,
       56,   56,   56,   56,   56,   61,   56,   56,   56,   56,
       56,   56,   56,   56,   56,    0,   56,   56,   56,   56,
       56
    } ;

static NFSv4yyconst flex_int16_t NFSv4yy_nxt[109] =
    {   0,
        4,    5,    6,    7,    4,    4,    8,    4,    4,    4,
        4,    9,    4,    4,    4,   10,   11,    4,   12,    4,
       13,   14,   15,    4,    4,    4,   26,   28,   47,   40,
       49,   27,   54,   53,   48,   29,   50,   32,   55,   52,
       30,   17,   17,   17,   17,   19,   19,   31,   31,   31,
       46,   46,   46,   51,   32,   45,   44,   43,   42,   41,
       32,   39,   38,   37,   36,   35,   34,   33,   56,   32,
       18,   16,   25,   24,   23,   22,   21,   20,   18,   16,
       56,    3,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56
    } ;

static NFSv4yyconst flex_int16_t NFSv4yy_chk[109] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   14,   15,   41,   60,
       42,   14,   52,   51,   41,   15,   42,   46,   52,   45,
       15,   57,   57,   57,   57,   58,   58,   59,   59,   59,
       61,   61,   61,   44,   40,   38,   36,   35,   34,   33,
       31,   30,   29,   28,   25,   24,   23,   22,   20,   19,
       17,   16,   13,   12,   11,   10,    9,    8,    7,    5,
        3,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56
    } ;

/* Table of booleans, true if rule could match eol. */
static NFSv4yyconst flex_int32_t NFSv4yy_rule_can_match_eol[22] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0,     };

extern int NFSv4yy_flex_debug;
int NFSv4yy_flex_debug = 0;

static NFSv4yy_state_type *NFSv4yy_state_buf=0, *NFSv4yy_state_ptr=0;
static char *NFSv4yy_full_match;
static int NFSv4yy_lp;
#define REJECT \
{ \
*NFSv4yy_cp = (NFSv4yy_hold_char); /* undo effects of setting up NFSv4yytext */ \
NFSv4yy_cp = (NFSv4yy_full_match); /* restore poss. backed-over text */ \
++(NFSv4yy_lp); \
goto find_rule; \
}

static int NFSv4yy_more_offset = 0;
static int NFSv4yy_prev_more_offset = 0;
#define NFSv4yymore() ((NFSv4yy_more_offset) = NFSv4yy_flex_strlen( NFSv4yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(NFSv4yy_more_offset) = (NFSv4yy_prev_more_offset); \
	NFSv4yyleng -= (NFSv4yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char NFSv4yytext[YYLMAX];
char *NFSv4yytext_ptr;
#line 1 "util/parser/lexer.l"
/*** WARNING - COMMENTS IN LEX MUST BE TAB INDENTED ***/
/* DEFINITIONS SECTION */
/* Everything between %{ ... %} is copied verbatim to the start of the lex generated C code. */
#line 7 "util/parser/lexer.l"
#include <string.h>
#include "cmpidt.h"
#include "parser.h"
#ifndef YY_FLEX_LEX_COMPAT
int NFSv4yylineno = 1;
#endif

char * NFSv4comments = NULL;		/* String buffer to accumulate comments */
/* Some useful regular expressions to use in the RULES section */
/* Use the default NFSv4yywrap() behavior */
/* END OF DEFINITIONS SECTION */
#line 558 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int NFSv4yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int NFSv4yylex_destroy (void );

int NFSv4yyget_debug (void );

void NFSv4yyset_debug (int debug_flag  );

YY_EXTRA_TYPE NFSv4yyget_extra (void );

void NFSv4yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *NFSv4yyget_in (void );

void NFSv4yyset_in  (FILE * in_str  );

FILE *NFSv4yyget_out (void );

void NFSv4yyset_out  (FILE * out_str  );

int NFSv4yyget_leng (void );

char *NFSv4yyget_text (void );

int NFSv4yyget_lineno (void );

void NFSv4yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int NFSv4yywrap (void );
#else
extern int NFSv4yywrap (void );
#endif
#endif

    static void NFSv4yyunput (int c,char *buf_ptr  );
    
#ifndef NFSv4yytext_ptr
static void NFSv4yy_flex_strncpy (char *,NFSv4yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int NFSv4yy_flex_strlen (NFSv4yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int NFSv4yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( NFSv4yytext, NFSv4yyleng, 1, NFSv4yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->NFSv4yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( NFSv4yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( NFSv4yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, NFSv4yyin))==0 && ferror(NFSv4yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(NFSv4yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "NFSv4yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef NFSv4yyterminate
#define NFSv4yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) NFSv4yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int NFSv4yylex (void);

#define YY_DECL int NFSv4yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after NFSv4yytext and NFSv4yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register NFSv4yy_state_type NFSv4yy_current_state;
	register char *NFSv4yy_cp, *NFSv4yy_bp;
	register int NFSv4yy_act;
    
#line 39 "util/parser/lexer.l"

	/* RULES SECTION */
	/* DESCRIBE EVERY LEXICAL TOKEN/PATTERN FOLLOWED BY THE APPROPRIATE ACTION.
	   TYPICALLY THE ACTION RETURNS THE TOKEN IDENTIFIER AND ITS VALUE (IN YYLVAL) */

	/* The following simple lexical tokens only return the token identifier */

#line 748 "<stdout>"

	if ( !(NFSv4yy_init) )
		{
		(NFSv4yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (NFSv4yy_state_buf) )
            (NFSv4yy_state_buf) = (NFSv4yy_state_type *)NFSv4yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (NFSv4yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in NFSv4yylex()" );

		if ( ! (NFSv4yy_start) )
			(NFSv4yy_start) = 1;	/* first start state */

		if ( ! NFSv4yyin )
			NFSv4yyin = stdin;

		if ( ! NFSv4yyout )
			NFSv4yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			NFSv4yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				NFSv4yy_create_buffer(NFSv4yyin,YY_BUF_SIZE );
		}

		NFSv4yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		NFSv4yy_cp = (NFSv4yy_c_buf_p);

		/* Support of NFSv4yytext. */
		*NFSv4yy_cp = (NFSv4yy_hold_char);

		/* NFSv4yy_bp points to the position in NFSv4yy_ch_buf of the start of
		 * the current run.
		 */
		NFSv4yy_bp = NFSv4yy_cp;

		NFSv4yy_current_state = (NFSv4yy_start);

		(NFSv4yy_state_ptr) = (NFSv4yy_state_buf);
		*(NFSv4yy_state_ptr)++ = NFSv4yy_current_state;

NFSv4yy_match:
		do
			{
			register YY_CHAR NFSv4yy_c = NFSv4yy_ec[YY_SC_TO_UI(*NFSv4yy_cp)];
			while ( NFSv4yy_chk[NFSv4yy_base[NFSv4yy_current_state] + NFSv4yy_c] != NFSv4yy_current_state )
				{
				NFSv4yy_current_state = (int) NFSv4yy_def[NFSv4yy_current_state];
				if ( NFSv4yy_current_state >= 57 )
					NFSv4yy_c = NFSv4yy_meta[(unsigned int) NFSv4yy_c];
				}
			NFSv4yy_current_state = NFSv4yy_nxt[NFSv4yy_base[NFSv4yy_current_state] + (unsigned int) NFSv4yy_c];
			*(NFSv4yy_state_ptr)++ = NFSv4yy_current_state;
			++NFSv4yy_cp;
			}
		while ( NFSv4yy_base[NFSv4yy_current_state] != 82 );

NFSv4yy_find_action:
		NFSv4yy_current_state = *--(NFSv4yy_state_ptr);
		(NFSv4yy_lp) = NFSv4yy_accept[NFSv4yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (NFSv4yy_lp) && (NFSv4yy_lp) < NFSv4yy_accept[NFSv4yy_current_state + 1] )
				{
				NFSv4yy_act = NFSv4yy_acclist[(NFSv4yy_lp)];
					{
					(NFSv4yy_full_match) = NFSv4yy_cp;
					break;
					}
				}
			--NFSv4yy_cp;
			NFSv4yy_current_state = *--(NFSv4yy_state_ptr);
			(NFSv4yy_lp) = NFSv4yy_accept[NFSv4yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( NFSv4yy_act != YY_END_OF_BUFFER && NFSv4yy_rule_can_match_eol[NFSv4yy_act] )
			{
			int NFSv4yyl;
			for ( NFSv4yyl = (NFSv4yy_prev_more_offset); NFSv4yyl < NFSv4yyleng; ++NFSv4yyl )
				if ( NFSv4yytext[NFSv4yyl] == '\n' )
					   
    NFSv4yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( NFSv4yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 46 "util/parser/lexer.l"
{
	return(PSEUDO);
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "util/parser/lexer.l"
{
	return(SECURITY);
	}
	YY_BREAK
/* The following lexical tokens return the token identifier and the value of the token (in NFSv4yylval) */
/* Security option keywords */
case 3:
#line 58 "util/parser/lexer.l"
case 4:
#line 59 "util/parser/lexer.l"
case 5:
#line 60 "util/parser/lexer.l"
case 6:
#line 61 "util/parser/lexer.l"
case 7:
#line 62 "util/parser/lexer.l"
case 8:
#line 63 "util/parser/lexer.l"
case 9:
#line 64 "util/parser/lexer.l"
case 10:
#line 65 "util/parser/lexer.l"
case 11:
#line 66 "util/parser/lexer.l"
case 12:
#line 67 "util/parser/lexer.l"
case 13:
#line 68 "util/parser/lexer.l"
case 14:
YY_RULE_SETUP
#line 68 "util/parser/lexer.l"
{
	NFSv4yylval.string = (char *)strdup(NFSv4yytext);
	return(SECURITY_VALUE);
	}
	YY_BREAK
/* Read-write permission keywords */
case 15:
#line 75 "util/parser/lexer.l"
case 16:
YY_RULE_SETUP
#line 75 "util/parser/lexer.l"
{
	NFSv4yylval.string = (char *)strdup(NFSv4yytext);
	return(PERMISSION);
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "util/parser/lexer.l"
{
	NFSv4yylval.string = (char *)strdup(NFSv4yytext);
	return(PATHNAME);
	}
	YY_BREAK
/* Ignore whitespace */
case 18:
YY_RULE_SETUP
#line 86 "util/parser/lexer.l"
;
	YY_BREAK
/* Ignore comments */
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 89 "util/parser/lexer.l"
{
	/* Extend the comments buffer */
	if (NFSv4comments == NULL) {
	   NFSv4comments = malloc(strlen(NFSv4yytext)+1);
	   strcpy(NFSv4comments,"");
	} else {
	   char * newcomments = malloc(strlen(NFSv4comments)+strlen(NFSv4yytext)+1);
	   strcpy(newcomments, NFSv4comments);
	   free(NFSv4comments);
	   NFSv4comments = newcomments;
	}

	/* Add this comment line to the comments buffer */
	strcat(NFSv4comments,NFSv4yytext);
	}
	YY_BREAK
/* Return single character punctuation characters as-is */
case 20:
YY_RULE_SETUP
#line 106 "util/parser/lexer.l"
{
	return(NFSv4yytext[0]);
	}
	YY_BREAK
/* END OF RULES SECTION */
case 21:
YY_RULE_SETUP
#line 111 "util/parser/lexer.l"
ECHO;
	YY_BREAK
#line 956 "<stdout>"
			case YY_STATE_EOF(INITIAL):
				NFSv4yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int NFSv4yy_amount_of_matched_text = (int) (NFSv4yy_cp - (NFSv4yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*NFSv4yy_cp = (NFSv4yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed NFSv4yyin at a new source and called
			 * NFSv4yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(NFSv4yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->NFSv4yy_input_file = NFSv4yyin;
			YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for NFSv4yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since NFSv4yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (NFSv4yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[(NFSv4yy_n_chars)] )
			{ /* This was really a NUL. */
			NFSv4yy_state_type NFSv4yy_next_state;

			(NFSv4yy_c_buf_p) = (NFSv4yytext_ptr) + NFSv4yy_amount_of_matched_text;

			NFSv4yy_current_state = NFSv4yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * NFSv4yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			NFSv4yy_next_state = NFSv4yy_try_NUL_trans( NFSv4yy_current_state );

			NFSv4yy_bp = (NFSv4yytext_ptr) + YY_MORE_ADJ;

			if ( NFSv4yy_next_state )
				{
				/* Consume the NUL. */
				NFSv4yy_cp = ++(NFSv4yy_c_buf_p);
				NFSv4yy_current_state = NFSv4yy_next_state;
				goto NFSv4yy_match;
				}

			else
				{
				NFSv4yy_cp = (NFSv4yy_c_buf_p);
				goto NFSv4yy_find_action;
				}
			}

		else switch ( NFSv4yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(NFSv4yy_did_buffer_switch_on_eof) = 0;

				if ( NFSv4yywrap( ) )
					{
					/* Note: because we've taken care in
					 * NFSv4yy_get_next_buffer() to have set up
					 * NFSv4yytext, we can now set up
					 * NFSv4yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(NFSv4yy_c_buf_p) = (NFSv4yytext_ptr) + YY_MORE_ADJ;

					NFSv4yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (NFSv4yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(NFSv4yy_c_buf_p) =
					(NFSv4yytext_ptr) + NFSv4yy_amount_of_matched_text;

				NFSv4yy_current_state = NFSv4yy_get_previous_state(  );

				NFSv4yy_cp = (NFSv4yy_c_buf_p);
				NFSv4yy_bp = (NFSv4yytext_ptr) + YY_MORE_ADJ;
				goto NFSv4yy_match;

			case EOB_ACT_LAST_MATCH:
				(NFSv4yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[(NFSv4yy_n_chars)];

				NFSv4yy_current_state = NFSv4yy_get_previous_state(  );

				NFSv4yy_cp = (NFSv4yy_c_buf_p);
				NFSv4yy_bp = (NFSv4yytext_ptr) + YY_MORE_ADJ;
				goto NFSv4yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of NFSv4yylex */

/* NFSv4yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int NFSv4yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf;
	register char *source = (NFSv4yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (NFSv4yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[(NFSv4yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->NFSv4yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (NFSv4yy_c_buf_p) - (NFSv4yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((NFSv4yy_c_buf_p) - (NFSv4yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars = (NFSv4yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[number_to_move]),
			(NFSv4yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars = (NFSv4yy_n_chars);
		}

	if ( (NFSv4yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			NFSv4yyrestart(NFSv4yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((NFSv4yy_size_t) ((NFSv4yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		NFSv4yy_size_t new_size = (NFSv4yy_n_chars) + number_to_move + ((NFSv4yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf = (char *) NFSv4yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv4yy_get_next_buffer()" );
	}

	(NFSv4yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[(NFSv4yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[(NFSv4yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(NFSv4yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[0];

	return ret_val;
}

/* NFSv4yy_get_previous_state - get the state just before the EOB char was reached */

    static NFSv4yy_state_type NFSv4yy_get_previous_state (void)
{
	register NFSv4yy_state_type NFSv4yy_current_state;
	register char *NFSv4yy_cp;
    
	NFSv4yy_current_state = (NFSv4yy_start);

	(NFSv4yy_state_ptr) = (NFSv4yy_state_buf);
	*(NFSv4yy_state_ptr)++ = NFSv4yy_current_state;

	for ( NFSv4yy_cp = (NFSv4yytext_ptr) + YY_MORE_ADJ; NFSv4yy_cp < (NFSv4yy_c_buf_p); ++NFSv4yy_cp )
		{
		register YY_CHAR NFSv4yy_c = (*NFSv4yy_cp ? NFSv4yy_ec[YY_SC_TO_UI(*NFSv4yy_cp)] : 1);
		while ( NFSv4yy_chk[NFSv4yy_base[NFSv4yy_current_state] + NFSv4yy_c] != NFSv4yy_current_state )
			{
			NFSv4yy_current_state = (int) NFSv4yy_def[NFSv4yy_current_state];
			if ( NFSv4yy_current_state >= 57 )
				NFSv4yy_c = NFSv4yy_meta[(unsigned int) NFSv4yy_c];
			}
		NFSv4yy_current_state = NFSv4yy_nxt[NFSv4yy_base[NFSv4yy_current_state] + (unsigned int) NFSv4yy_c];
		*(NFSv4yy_state_ptr)++ = NFSv4yy_current_state;
		}

	return NFSv4yy_current_state;
}

/* NFSv4yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = NFSv4yy_try_NUL_trans( current_state );
 */
    static NFSv4yy_state_type NFSv4yy_try_NUL_trans  (NFSv4yy_state_type NFSv4yy_current_state )
{
	register int NFSv4yy_is_jam;
    
	register YY_CHAR NFSv4yy_c = 1;
	while ( NFSv4yy_chk[NFSv4yy_base[NFSv4yy_current_state] + NFSv4yy_c] != NFSv4yy_current_state )
		{
		NFSv4yy_current_state = (int) NFSv4yy_def[NFSv4yy_current_state];
		if ( NFSv4yy_current_state >= 57 )
			NFSv4yy_c = NFSv4yy_meta[(unsigned int) NFSv4yy_c];
		}
	NFSv4yy_current_state = NFSv4yy_nxt[NFSv4yy_base[NFSv4yy_current_state] + (unsigned int) NFSv4yy_c];
	NFSv4yy_is_jam = (NFSv4yy_current_state == 56);
	if ( ! NFSv4yy_is_jam )
		*(NFSv4yy_state_ptr)++ = NFSv4yy_current_state;

	return NFSv4yy_is_jam ? 0 : NFSv4yy_current_state;
}

    static void NFSv4yyunput (int c, register char * NFSv4yy_bp )
{
	register char *NFSv4yy_cp;
    
    NFSv4yy_cp = (NFSv4yy_c_buf_p);

	/* undo effects of setting up NFSv4yytext */
	*NFSv4yy_cp = (NFSv4yy_hold_char);

	if ( NFSv4yy_cp < YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (NFSv4yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf )
			*--dest = *--source;

		NFSv4yy_cp += (int) (dest - source);
		NFSv4yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars =
			(NFSv4yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_size;

		if ( NFSv4yy_cp < YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--NFSv4yy_cp = (char) c;

    if ( c == '\n' ){
        --NFSv4yylineno;
    }

	(NFSv4yytext_ptr) = NFSv4yy_bp;
	(NFSv4yy_hold_char) = *NFSv4yy_cp;
	(NFSv4yy_c_buf_p) = NFSv4yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int NFSv4yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(NFSv4yy_c_buf_p) = (NFSv4yy_hold_char);

	if ( *(NFSv4yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* NFSv4yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (NFSv4yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->NFSv4yy_ch_buf[(NFSv4yy_n_chars)] )
			/* This was really a NUL. */
			*(NFSv4yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (NFSv4yy_c_buf_p) - (NFSv4yytext_ptr);
			++(NFSv4yy_c_buf_p);

			switch ( NFSv4yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because NFSv4yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					NFSv4yyrestart(NFSv4yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( NFSv4yywrap( ) )
						return EOF;

					if ( ! (NFSv4yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return NFSv4yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(NFSv4yy_c_buf_p) = (NFSv4yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (NFSv4yy_c_buf_p);	/* cast for 8-bit char's */
	*(NFSv4yy_c_buf_p) = '\0';	/* preserve NFSv4yytext */
	(NFSv4yy_hold_char) = *++(NFSv4yy_c_buf_p);

	if ( c == '\n' )
		   
    NFSv4yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void NFSv4yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        NFSv4yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            NFSv4yy_create_buffer(NFSv4yyin,YY_BUF_SIZE );
	}

	NFSv4yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	NFSv4yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void NFSv4yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		NFSv4yypop_buffer_state();
	 *		NFSv4yypush_buffer_state(new_buffer);
     */
	NFSv4yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(NFSv4yy_c_buf_p) = (NFSv4yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_pos = (NFSv4yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars = (NFSv4yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	NFSv4yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (NFSv4yywrap()) processing, but the only time this flag
	 * is looked at is after NFSv4yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(NFSv4yy_did_buffer_switch_on_eof) = 1;
}

static void NFSv4yy_load_buffer_state  (void)
{
    	(NFSv4yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars;
	(NFSv4yytext_ptr) = (NFSv4yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_pos;
	NFSv4yyin = YY_CURRENT_BUFFER_LVALUE->NFSv4yy_input_file;
	(NFSv4yy_hold_char) = *(NFSv4yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE NFSv4yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) NFSv4yyalloc(sizeof( struct NFSv4yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv4yy_create_buffer()" );

	b->NFSv4yy_buf_size = size;

	/* NFSv4yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->NFSv4yy_ch_buf = (char *) NFSv4yyalloc(b->NFSv4yy_buf_size + 2  );
	if ( ! b->NFSv4yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv4yy_create_buffer()" );

	b->NFSv4yy_is_our_buffer = 1;

	NFSv4yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with NFSv4yy_create_buffer()
 * 
 */
    void NFSv4yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->NFSv4yy_is_our_buffer )
		NFSv4yyfree((void *) b->NFSv4yy_ch_buf  );

	NFSv4yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a NFSv4yyrestart() or at EOF.
 */
    static void NFSv4yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	NFSv4yy_flush_buffer(b );

	b->NFSv4yy_input_file = file;
	b->NFSv4yy_fill_buffer = 1;

    /* If b is the current buffer, then NFSv4yy_init_buffer was _probably_
     * called from NFSv4yyrestart() or through NFSv4yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->NFSv4yy_bs_lineno = 1;
        b->NFSv4yy_bs_column = 0;
    }

        b->NFSv4yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void NFSv4yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->NFSv4yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->NFSv4yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->NFSv4yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->NFSv4yy_buf_pos = &b->NFSv4yy_ch_buf[0];

	b->NFSv4yy_at_bol = 1;
	b->NFSv4yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		NFSv4yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void NFSv4yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	NFSv4yyensure_buffer_stack();

	/* This block is copied from NFSv4yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(NFSv4yy_c_buf_p) = (NFSv4yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_buf_pos = (NFSv4yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->NFSv4yy_n_chars = (NFSv4yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(NFSv4yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from NFSv4yy_switch_to_buffer. */
	NFSv4yy_load_buffer_state( );
	(NFSv4yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void NFSv4yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	NFSv4yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((NFSv4yy_buffer_stack_top) > 0)
		--(NFSv4yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		NFSv4yy_load_buffer_state( );
		(NFSv4yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void NFSv4yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(NFSv4yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(NFSv4yy_buffer_stack) = (struct NFSv4yy_buffer_state**)NFSv4yyalloc
								(num_to_alloc * sizeof(struct NFSv4yy_buffer_state*)
								);
		if ( ! (NFSv4yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv4yyensure_buffer_stack()" );
								  
		memset((NFSv4yy_buffer_stack), 0, num_to_alloc * sizeof(struct NFSv4yy_buffer_state*));
				
		(NFSv4yy_buffer_stack_max) = num_to_alloc;
		(NFSv4yy_buffer_stack_top) = 0;
		return;
	}

	if ((NFSv4yy_buffer_stack_top) >= ((NFSv4yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (NFSv4yy_buffer_stack_max) + grow_size;
		(NFSv4yy_buffer_stack) = (struct NFSv4yy_buffer_state**)NFSv4yyrealloc
								((NFSv4yy_buffer_stack),
								num_to_alloc * sizeof(struct NFSv4yy_buffer_state*)
								);
		if ( ! (NFSv4yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in NFSv4yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((NFSv4yy_buffer_stack) + (NFSv4yy_buffer_stack_max), 0, grow_size * sizeof(struct NFSv4yy_buffer_state*));
		(NFSv4yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE NFSv4yy_scan_buffer  (char * base, NFSv4yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) NFSv4yyalloc(sizeof( struct NFSv4yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv4yy_scan_buffer()" );

	b->NFSv4yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->NFSv4yy_buf_pos = b->NFSv4yy_ch_buf = base;
	b->NFSv4yy_is_our_buffer = 0;
	b->NFSv4yy_input_file = 0;
	b->NFSv4yy_n_chars = b->NFSv4yy_buf_size;
	b->NFSv4yy_is_interactive = 0;
	b->NFSv4yy_at_bol = 1;
	b->NFSv4yy_fill_buffer = 0;
	b->NFSv4yy_buffer_status = YY_BUFFER_NEW;

	NFSv4yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to NFSv4yylex() will
 * scan from a @e copy of @a str.
 * @param NFSv4yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       NFSv4yy_scan_bytes() instead.
 */
YY_BUFFER_STATE NFSv4yy_scan_string (NFSv4yyconst char * NFSv4yystr )
{
    
	return NFSv4yy_scan_bytes(NFSv4yystr,strlen(NFSv4yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to NFSv4yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE NFSv4yy_scan_bytes  (NFSv4yyconst char * NFSv4yybytes, int  _NFSv4yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	NFSv4yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _NFSv4yybytes_len + 2;
	buf = (char *) NFSv4yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in NFSv4yy_scan_bytes()" );

	for ( i = 0; i < _NFSv4yybytes_len; ++i )
		buf[i] = NFSv4yybytes[i];

	buf[_NFSv4yybytes_len] = buf[_NFSv4yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = NFSv4yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in NFSv4yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->NFSv4yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void NFSv4yy_fatal_error (NFSv4yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine NFSv4yyless() so it works in section 3 code. */

#undef NFSv4yyless
#define NFSv4yyless(n) \
	do \
		{ \
		/* Undo effects of setting up NFSv4yytext. */ \
        int NFSv4yyless_macro_arg = (n); \
        YY_LESS_LINENO(NFSv4yyless_macro_arg);\
		NFSv4yytext[NFSv4yyleng] = (NFSv4yy_hold_char); \
		(NFSv4yy_c_buf_p) = NFSv4yytext + NFSv4yyless_macro_arg; \
		(NFSv4yy_hold_char) = *(NFSv4yy_c_buf_p); \
		*(NFSv4yy_c_buf_p) = '\0'; \
		NFSv4yyleng = NFSv4yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int NFSv4yyget_lineno  (void)
{
        
    return NFSv4yylineno;
}

/** Get the input stream.
 * 
 */
FILE *NFSv4yyget_in  (void)
{
        return NFSv4yyin;
}

/** Get the output stream.
 * 
 */
FILE *NFSv4yyget_out  (void)
{
        return NFSv4yyout;
}

/** Get the length of the current token.
 * 
 */
int NFSv4yyget_leng  (void)
{
        return NFSv4yyleng;
}

/** Get the current token.
 * 
 */

char *NFSv4yyget_text  (void)
{
        return NFSv4yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void NFSv4yyset_lineno (int  line_number )
{
    
    NFSv4yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see NFSv4yy_switch_to_buffer
 */
void NFSv4yyset_in (FILE *  in_str )
{
        NFSv4yyin = in_str ;
}

void NFSv4yyset_out (FILE *  out_str )
{
        NFSv4yyout = out_str ;
}

int NFSv4yyget_debug  (void)
{
        return NFSv4yy_flex_debug;
}

void NFSv4yyset_debug (int  bdebug )
{
        NFSv4yy_flex_debug = bdebug ;
}

static int NFSv4yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from NFSv4yylex_destroy(), so don't allocate here.
     */

    /* We do not touch NFSv4yylineno unless the option is enabled. */
    NFSv4yylineno =  1;
    
    (NFSv4yy_buffer_stack) = 0;
    (NFSv4yy_buffer_stack_top) = 0;
    (NFSv4yy_buffer_stack_max) = 0;
    (NFSv4yy_c_buf_p) = (char *) 0;
    (NFSv4yy_init) = 0;
    (NFSv4yy_start) = 0;

    (NFSv4yy_state_buf) = 0;
    (NFSv4yy_state_ptr) = 0;
    (NFSv4yy_full_match) = 0;
    (NFSv4yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    NFSv4yyin = stdin;
    NFSv4yyout = stdout;
#else
    NFSv4yyin = (FILE *) 0;
    NFSv4yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * NFSv4yylex_init()
     */
    return 0;
}

/* NFSv4yylex_destroy is for both reentrant and non-reentrant scanners. */
int NFSv4yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		NFSv4yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		NFSv4yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	NFSv4yyfree((NFSv4yy_buffer_stack) );
	(NFSv4yy_buffer_stack) = NULL;

    NFSv4yyfree ( (NFSv4yy_state_buf) );
    (NFSv4yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * NFSv4yylex() is called, initialization will occur. */
    NFSv4yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef NFSv4yytext_ptr
static void NFSv4yy_flex_strncpy (char* s1, NFSv4yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int NFSv4yy_flex_strlen (NFSv4yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *NFSv4yyalloc (NFSv4yy_size_t  size )
{
	return (void *) malloc( size );
}

void *NFSv4yyrealloc  (void * ptr, NFSv4yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void NFSv4yyfree (void * ptr )
{
	free( (char *) ptr );	/* see NFSv4yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "NFSv4yytables"

#line 111 "util/parser/lexer.l"


	/* USER SUBROUTINE SECTION */
	/* Everything below is copied verbatim to the end of the lex generated C code. */

void NFSv4yyerror(char *errmsg)
{
   fprintf(stderr, "NFSv4 parser, line %d: %s at '%s'\n", NFSv4yylineno, errmsg, NFSv4yytext);
}


